const request = require('supertest');
const app = require('../index') // Import your routes file

describe('POST /encode', () => {
    it('should return a 201 status code and encoded URL on success', async () => {
        const originalUrl = 'https://jaachi-portfolio.netlify.app/';
        const response = await request(app)
            .post('/encode')
            .send({ originalUrl });

        expect(response.statusCode).toBe(201);
        expect(response.body).toHaveProperty('originalUrl', originalUrl);
        expect(response.body).toHaveProperty('shortUrl'); // Assumed to be generated by shortid
    });

    it('should return a 400 status code on missing original URL', async () => {
        const response = await request(app)
            .post('/encode')
            .send({});

        expect(response.statusCode).toBe(500); // Or a more specific error code if applicable
    });

    // Add more test cases for error handling and edge cases (optional)
});
